name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 5
    name: Test
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Build and test API
      run: |
        cd client
        npm install
        npm start &
        sleep 5
        cd ..
        cd api
        npm install
        npm start &
        sleep 5
        npm test 