name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 
on: 
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Build and run Docker containers
      run: |
        docker-compose up -d    
    
    - name: Build and test API
      working-directory: api
      run: |
        google-chrome --product-version
        chmod -R 777 test/chromedriver.exe
        npm install
        npm install -g chromedriver
        npm test

    - name: Tear down Docker containers
      run: |
        docker-compose down